// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuw-UrDvd88HztjFZcI_PecIJHeQpxLoQ',
    appId: '1:366910244785:web:da538157e59e3e43be9f90',
    messagingSenderId: '366910244785',
    projectId: 'boravaleno',
    authDomain: 'boravaleno.firebaseapp.com',
    storageBucket: 'boravaleno.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxbJljK_sUczr-O-US4mzrHougvhgdWc0',
    appId: '1:366910244785:android:91068fd5a521ab3dbe9f90',
    messagingSenderId: '366910244785',
    projectId: 'boravaleno',
    storageBucket: 'boravaleno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48ztY95OsmBQgf0kD2E7HwmtcDF5M3tQ',
    appId: '1:366910244785:ios:428c073bbe9c2342be9f90',
    messagingSenderId: '366910244785',
    projectId: 'boravaleno',
    storageBucket: 'boravaleno.appspot.com',
    iosBundleId: 'com.example.boravaleno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC48ztY95OsmBQgf0kD2E7HwmtcDF5M3tQ',
    appId: '1:366910244785:ios:428c073bbe9c2342be9f90',
    messagingSenderId: '366910244785',
    projectId: 'boravaleno',
    storageBucket: 'boravaleno.appspot.com',
    iosBundleId: 'com.example.boravaleno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuw-UrDvd88HztjFZcI_PecIJHeQpxLoQ',
    appId: '1:366910244785:web:015abf33ed6aeff3be9f90',
    messagingSenderId: '366910244785',
    projectId: 'boravaleno',
    authDomain: 'boravaleno.firebaseapp.com',
    storageBucket: 'boravaleno.appspot.com',
  );
}
